title: daniel-plisetsky

me:
  name: Daniel Plisetsky
  email: danplisetsky@gmail.com
  email_title: shoot me a letter
  github: https://github.com/danplisetsky
  github_title: check out the source code
  medium: https://medium.com/@danielplisetsky
  medium_title: join the discussion
  rss: "/feed.xml"
  rss_title: stay apprised of the upcoming posts

strict_front_matter: true

# default values for pages and posts

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Daniel Plisetsky, software developer and freelance journalist
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-paginate

#pagination optioms
paginate: 3

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
